### ISSUE TITLE
Can still die to fluid/cargo wagons

### ISSUE THREAD

**Issue by mschurr** [cdaringe/nice-try-train#2]
You need to check for cargo / fluid wagons, too. Otherwise, you can still die if you walk into one of those on a moving train.

**Comment by cdaringe** [comment]
You're correct.  I thought I had already landed a patch for that...

**Comment by cdaringe** [comment]
1.1.0 now protects from cargo & fluid wagons :)

all it took was me dying enough to motivate!

**Comment by cdaringe** [comment]
grumbles... https://forums.factorio.com/viewtopic.php?f=189&t=64896&p=398282#p398282
