### ISSUE TITLE
Crash when getting killed by train

### ISSUE THREAD

**Issue by Aplyde** [cdaringe/nice-try-train#8]
The mod Nice Try, Train (1.4.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event nice-try-train::on_pre_player_died (ID 40)
__nice-try-train__/control.lua:3: attempt to index field 'nice-try-train-friendly-setting' (a nil value)
stack traceback:
	__nice-try-train__/control.lua:3: in function <__nice-try-train__/control.lua:1>

Happens with all other mods disabled.

**Comment by Aplyde** [comment]
The settings.lua seems to be missing

**Comment by undermark5** [comment]
Haha, yup, looks like I forgot to modify the release script to include it. Sorry about that. I'll get working on fixing this right away

**Comment by undermark5** [comment]
Alright I think I've got this fixed now. Please let me know if you come across any other issues
