### ISSUE TITLE
Update for Factorio v1.1

### ISSUE THREAD

**Issue by DatenNirwana** [cdaringe/nice-try-train#9]
Hi,

currently the mod isn't compatible for upcoming Factorio release v1.1. Can you pelae update the mod for it? Thanks! :-)

**Comment by cdaringe** [comment]
I am not active playing factorio anymore. You are welcome to fork it and
publish independently!

**Comment by DatenNirwana** [comment]
Thanks for the infomation. I'll think about a fork.

**Comment by undermark5** [comment]
@DatenNirwana I'll get it updated today. I haven't been playing on the experimental branch yet, but I'm going to start today. It hasn't been a huge priority for me due to work and life in general, but I will push an update out today.

**Comment by DatenNirwana** [comment]
@undermark5,

Thank you a lot. :-)

**Comment by undermark5** [comment]
@DatenNirwana just published the update. Reopen this issue and let me know if you have any problems.

**Comment by cdaringe** [comment]
Send me your fork links and i minimally will update the readme to point to your project :)

**Comment by cdaringe** [comment]
oh, undermark5 is already a contributor 😆 . whatever works
